name: "SQL Project Analysis Action"
description: "analysis a database project using msbuild code scan"
inputs:
  source-path:
    description: "Path of the SQL project."
    required: true
  outfile-path:
    description: "Path of scan result file"
    required: false
  msbuild-arguments:
    description: "msbuild argumnets."
    default: "-t:build,SqlStaticCodeAnalysis /p:RunSqlCodeAnalysis=True /p:SqlCodeAnalysisRules=''"
    required: false
runs:
  using: "node12"
  main: "lib/action.js"
