name: "Build"

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:

    runs-on: [self-hosted]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
          node-version: 16
          cache: 'npm'

    - name: install node_modules
      run: npm install

    - name: Generate Static Code Analysis Result
      run: npm run build
